// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moda_Praia.Data;

#nullable disable

namespace Moda_Praia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251023205131_atributoZeroParaEstoque02")]
    partial class atributoZeroParaEstoque02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Moda_Praia.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Moda_Praia.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CorBase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoCusto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            CorBase = "Multicolorido",
                            Descricao = "Biquíni cortininha com estampa floral vibrante, ideal para os dias de sol.",
                            Nome = "Biquíni Cortininha Estampado Floral",
                            PrecoCusto = 35.50m,
                            PrecoVenda = 79.90m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            CorBase = "Azul",
                            Descricao = "Maiô estilo engana mamãe em tecido liso azul, elegante e confortável.",
                            Nome = "Maiô Engana Mamãe Liso Azul",
                            PrecoCusto = 45.00m,
                            PrecoVenda = 99.90m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            CorBase = "Branco",
                            Descricao = "Saída de praia longa em renda branca, perfeita para um look sofisticado.",
                            Nome = "Saída de Praia Longa Renda Branca",
                            PrecoCusto = 60.00m,
                            PrecoVenda = 129.90m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            CorBase = "Preto",
                            Descricao = "Sungão modelo boxer em tecido liso preto, confortável e com bom ajuste.",
                            Nome = "Sungão Boxer Liso Preto",
                            PrecoCusto = 28.00m,
                            PrecoVenda = 59.90m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            CorBase = "Branco com Poá Preto",
                            Descricao = "Biquíni tomara que caia com estampa de poá clássica e charmosa.",
                            Nome = "Biquíni Tomara que Caia Poá",
                            PrecoCusto = 40.00m,
                            PrecoVenda = 89.90m
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 2,
                            CorBase = "Multicolorido",
                            Descricao = "Maiô com corte cavado e estampa tropical vibrante, para um visual moderno.",
                            Nome = "Maiô Cavado Estampado Tropical",
                            PrecoCusto = 50.00m,
                            PrecoVenda = 109.90m
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 3,
                            CorBase = "Bege",
                            Descricao = "Saída de praia curta em crochê, leve e estilosa para os dias quentes.",
                            Nome = "Saída de Praia Curta Crochê",
                            PrecoCusto = 45.00m,
                            PrecoVenda = 99.90m
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 1,
                            CorBase = "Azul com Listras Brancas",
                            Descricao = "Sungão modelo slip com estampa listrada, confortável e com ótimo caimento.",
                            Nome = "Sungão Slip Listrado",
                            PrecoCusto = 22.00m,
                            PrecoVenda = 49.90m
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 1,
                            CorBase = "Vermelho",
                            Descricao = "Biquíni modelo cropped em tecido liso vermelho, moderno e estiloso.",
                            Nome = "Biquíni Cropped Liso Vermelho",
                            PrecoCusto = 42.00m,
                            PrecoVenda = 94.90m
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 2,
                            CorBase = "Preto com Flores",
                            Descricao = "Maiô plus size com estampa floral em tons escuros, elegante e confortável.",
                            Nome = "Maiô Plus Size Floral Escuro",
                            PrecoCusto = 55.00m,
                            PrecoVenda = 119.90m
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 3,
                            CorBase = "Estampado",
                            Descricao = "Saída de praia modelo vestido com estampa colorida, prático e charmoso.",
                            Nome = "Saída de Praia Vestido Estampado",
                            PrecoCusto = 52.00m,
                            PrecoVenda = 114.90m
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 1,
                            CorBase = "Multicolorido",
                            Descricao = "Sungão com estampa abstrata moderna, para um visual diferenciado.",
                            Nome = "Sungão Estampado Abstrato",
                            PrecoCusto = 30.00m,
                            PrecoVenda = 64.90m
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 1,
                            CorBase = "Preto",
                            Descricao = "Biquíni modelo hot pant em tecido liso preto, elegante e com bom caimento.",
                            Nome = "Biquíni Hot Pant Liso Preto",
                            PrecoCusto = 45.00m,
                            PrecoVenda = 99.90m
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 2,
                            CorBase = "Verde Água",
                            Descricao = "Maiô com bojo em tecido liso verde água, confortável e com bom suporte.",
                            Nome = "Maiô com Bojo Liso Verde Água",
                            PrecoCusto = 48.00m,
                            PrecoVenda = 104.90m
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 3,
                            CorBase = "Branco com Listras Azuis",
                            Descricao = "Saída de praia modelo camisa com estampa listrada, moderna e versátil.",
                            Nome = "Saída de Praia Camisa Listrada",
                            PrecoCusto = 50.00m,
                            PrecoVenda = 109.90m
                        });
                });

            modelBuilder.Entity("Moda_Praia.Models.ProdutoImagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutoImagens");
                });

            modelBuilder.Entity("Moda_Praia.Models.ProdutoTamanho", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("TamanhoId")
                        .HasColumnType("int");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.HasKey("ProdutoId", "TamanhoId");

                    b.HasIndex("TamanhoId");

                    b.ToTable("ProdutoTamanhos");
                });

            modelBuilder.Entity("Moda_Praia.Models.Tamanho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tamanhos");
                });

            modelBuilder.Entity("Moda_Praia.Models.Produto", b =>
                {
                    b.HasOne("Moda_Praia.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Moda_Praia.Models.ProdutoImagem", b =>
                {
                    b.HasOne("Moda_Praia.Models.Produto", "Produto")
                        .WithMany("ProdutoImagens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Moda_Praia.Models.ProdutoTamanho", b =>
                {
                    b.HasOne("Moda_Praia.Models.Produto", "Produto")
                        .WithMany("ProdutoTamanhos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moda_Praia.Models.Tamanho", "Tamanho")
                        .WithMany("ProdutoTamanhos")
                        .HasForeignKey("TamanhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Tamanho");
                });

            modelBuilder.Entity("Moda_Praia.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Moda_Praia.Models.Produto", b =>
                {
                    b.Navigation("ProdutoImagens");

                    b.Navigation("ProdutoTamanhos");
                });

            modelBuilder.Entity("Moda_Praia.Models.Tamanho", b =>
                {
                    b.Navigation("ProdutoTamanhos");
                });
#pragma warning restore 612, 618
        }
    }
}
