// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moda_Praia.Data;

#nullable disable

namespace Moda_Praia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250721192514_tabelaImagem_Produto_Precisao02")]
    partial class tabelaImagem_Produto_Precisao02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Moda_Praia.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorBase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoCusto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("QuantidadeEstoque")
                        .HasColumnType("int");

                    b.Property<string>("urlName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Biquínis",
                            CorBase = "Multicolorido",
                            Descricao = "Biquíni cortininha com estampa floral vibrante, ideal para os dias de sol.",
                            Nome = "Biquíni Cortininha Estampado Floral",
                            PrecoCusto = 35.50m,
                            PrecoVenda = 79.90m,
                            QuantidadeEstoque = 50,
                            urlName = "biquini-cortininha-floral"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Maiôs",
                            CorBase = "Azul",
                            Descricao = "Maiô estilo engana mamãe em tecido liso azul, elegante e confortável.",
                            Nome = "Maiô Engana Mamãe Liso Azul",
                            PrecoCusto = 45.00m,
                            PrecoVenda = 99.90m,
                            QuantidadeEstoque = 30,
                            urlName = "maio-engana-mamae-azul"
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Saídas de Praia",
                            CorBase = "Branco",
                            Descricao = "Saída de praia longa em renda branca, perfeita para um look sofisticado.",
                            Nome = "Saída de Praia Longa Renda Branca",
                            PrecoCusto = 60.00m,
                            PrecoVenda = 129.90m,
                            QuantidadeEstoque = 25,
                            urlName = "saida-praia-longa-renda-branca"
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Sungas",
                            CorBase = "Preto",
                            Descricao = "Sungão modelo boxer em tecido liso preto, confortável e com bom ajuste.",
                            Nome = "Sungão Boxer Liso Preto",
                            PrecoCusto = 28.00m,
                            PrecoVenda = 59.90m,
                            QuantidadeEstoque = 40,
                            urlName = "sungao-boxer-preto"
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Biquínis",
                            CorBase = "Branco com Poá Preto",
                            Descricao = "Biquíni tomara que caia com estampa de poá clássica e charmosa.",
                            Nome = "Biquíni Tomara que Caia Poá",
                            PrecoCusto = 40.00m,
                            PrecoVenda = 89.90m,
                            QuantidadeEstoque = 35,
                            urlName = "biquini-tomara-que-caia-poa"
                        },
                        new
                        {
                            Id = 6,
                            Categoria = "Maiôs",
                            CorBase = "Multicolorido",
                            Descricao = "Maiô com corte cavado e estampa tropical vibrante, para um visual moderno.",
                            Nome = "Maiô Cavado Estampado Tropical",
                            PrecoCusto = 50.00m,
                            PrecoVenda = 109.90m,
                            QuantidadeEstoque = 20,
                            urlName = "maio-cavado-estampado-tropical"
                        },
                        new
                        {
                            Id = 7,
                            Categoria = "Saídas de Praia",
                            CorBase = "Bege",
                            Descricao = "Saída de praia curta em crochê, leve e estilosa para os dias quentes.",
                            Nome = "Saída de Praia Curta Crochê",
                            PrecoCusto = 45.00m,
                            PrecoVenda = 99.90m,
                            QuantidadeEstoque = 30,
                            urlName = "saida-praia-curta-croche"
                        },
                        new
                        {
                            Id = 8,
                            Categoria = "Sungas",
                            CorBase = "Azul com Listras Brancas",
                            Descricao = "Sungão modelo slip com estampa listrada, confortável e com ótimo caimento.",
                            Nome = "Sungão Slip Listrado",
                            PrecoCusto = 22.00m,
                            PrecoVenda = 49.90m,
                            QuantidadeEstoque = 55,
                            urlName = "sungao-slip-listrado"
                        },
                        new
                        {
                            Id = 9,
                            Categoria = "Biquínis",
                            CorBase = "Vermelho",
                            Descricao = "Biquíni modelo cropped em tecido liso vermelho, moderno e estiloso.",
                            Nome = "Biquíni Cropped Liso Vermelho",
                            PrecoCusto = 42.00m,
                            PrecoVenda = 94.90m,
                            QuantidadeEstoque = 45,
                            urlName = "biquini-cropped-vermelho"
                        },
                        new
                        {
                            Id = 10,
                            Categoria = "Maiôs",
                            CorBase = "Preto com Flores",
                            Descricao = "Maiô plus size com estampa floral em tons escuros, elegante e confortável.",
                            Nome = "Maiô Plus Size Floral Escuro",
                            PrecoCusto = 55.00m,
                            PrecoVenda = 119.90m,
                            QuantidadeEstoque = 15,
                            urlName = "maio-plus-size-floral-escuro"
                        },
                        new
                        {
                            Id = 11,
                            Categoria = "Saídas de Praia",
                            CorBase = "Estampado",
                            Descricao = "Saída de praia modelo vestido com estampa colorida, prático e charmoso.",
                            Nome = "Saída de Praia Vestido Estampado",
                            PrecoCusto = 52.00m,
                            PrecoVenda = 114.90m,
                            QuantidadeEstoque = 28,
                            urlName = "saida-praia-vestido-estampado"
                        },
                        new
                        {
                            Id = 12,
                            Categoria = "Sungas",
                            CorBase = "Multicolorido",
                            Descricao = "Sungão com estampa abstrata moderna, para um visual diferenciado.",
                            Nome = "Sungão Estampado Abstrato",
                            PrecoCusto = 30.00m,
                            PrecoVenda = 64.90m,
                            QuantidadeEstoque = 38,
                            urlName = "sungao-estampado-abstrato"
                        },
                        new
                        {
                            Id = 13,
                            Categoria = "Biquínis",
                            CorBase = "Preto",
                            Descricao = "Biquíni modelo hot pant em tecido liso preto, elegante e com bom caimento.",
                            Nome = "Biquíni Hot Pant Liso Preto",
                            PrecoCusto = 45.00m,
                            PrecoVenda = 99.90m,
                            QuantidadeEstoque = 42,
                            urlName = "biquini-hot-pant-preto"
                        },
                        new
                        {
                            Id = 14,
                            Categoria = "Maiôs",
                            CorBase = "Verde Água",
                            Descricao = "Maiô com bojo em tecido liso verde água, confortável e com bom suporte.",
                            Nome = "Maiô com Bojo Liso Verde Água",
                            PrecoCusto = 48.00m,
                            PrecoVenda = 104.90m,
                            QuantidadeEstoque = 22,
                            urlName = "maio-com-bojo-verde-agua"
                        },
                        new
                        {
                            Id = 15,
                            Categoria = "Saídas de Praia",
                            CorBase = "Branco com Listras Azuis",
                            Descricao = "Saída de praia modelo camisa com estampa listrada, moderna e versátil.",
                            Nome = "Saída de Praia Camisa Listrada",
                            PrecoCusto = 50.00m,
                            PrecoVenda = 109.90m,
                            QuantidadeEstoque = 33,
                            urlName = "saida-praia-camisa-listrada"
                        });
                });

            modelBuilder.Entity("Moda_Praia.Models.ProdutoImagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutoImagem");
                });

            modelBuilder.Entity("Moda_Praia.Models.ProdutoImagem", b =>
                {
                    b.HasOne("Moda_Praia.Models.Produto", "Produto")
                        .WithMany("produtoImagems")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Moda_Praia.Models.Produto", b =>
                {
                    b.Navigation("produtoImagems");
                });
#pragma warning restore 612, 618
        }
    }
}
